name: Auto-create PR

# Runs when called from another workflow
on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      head_branch:
        required: true
        type: string
      title:
        required: true
        type: string
      body:
        required: true
        type: string
    secrets:
      gh_token:
        required: true

# Use default github actions token for gh CLI
env:
  GITHUB_TOKEN: ${{ secrets.gh_token }}

jobs:
  # Job to check for existing PR with the same branches
  # and if there are differences between the branches
  check-for-existing-pr:
    name: Check for existing pull request

    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      contents: read

    outputs:
      prs: ${{ steps.check.outputs.prs }}
      files_changed: ${{ steps.check.outputs.files_changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Output PR list JSON to prs and diff status code to files_changed
      - id: check
        name: Check for existing PRs
        run: | 
          prs_json=$(gh pr list --state open \
            --base ${{ inputs.base_branch }} \
            --head ${{ inputs.head_branch }} \
            --json url)
          echo $prs_json
          echo "::set-output name=prs::$prs_json"
          
          git fetch
          # Use || to prevent script from exiting on non-zero exit code
          git diff remotes/origin/${{ inputs.base_branch }}..remotes/origin/${{ inputs.head_branch }} --quiet || diff_code=$?
          if [ $diff_code != '1' ] && [ $diff_code != '0' ]; then exit $diff_code; fi
          echo "git diff code: $diff_code"
          echo "::set-output name=files_changed::$diff_code"

  # Job to create a pull request
  create-pr:
    name: Create pull request

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      repository-projects: read  # Needed to add labels

    needs: check-for-existing-pr

    # Only run if no existing release PRs exist and there is a difference between the branches (no run for merge commits)
    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] == null && needs.check-for-existing-pr.outputs.files_changed == '1' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          gh pr create \
            --base ${{ inputs.base_branch }} \
            --head ${{ inputs.head_branch }} \
            --title "${{ inputs.title }}" \
            --body "${{ inputs.body }}" \
            --label release

      # Adding labels in one step using the CLI doesn't work via actions
      - name: Add release label
        run: |
          pr_num=$(gh pr list --state open \
            --base ${{ inputs.base_branch }} \
            --head ${{ inputs.head_branch }} \
            --json number | jq '.[0].number')
          gh pr edit $pr_num --add-label release
