name: Auto-create PR

# Runs when called from another workflow
on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      head_branch:
        required: true
        type: string
    secrets:
      gh_token:
        required: true

# Use default github actions token for gh CLI
env:
  GITHUB_TOKEN: ${{ secrets.gh_token }}

jobs:
  check-for-existing-pr:
    name: Check for existing PR

    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      contents: read

    outputs:
      prs: ${{ steps.check.outputs.prs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Output JSON to output called prs
      - id: check
        name: Check for existing PRs
        run: | 
          echo ${{ inputs.base_branch }}
          echo ${{ inputs.head_branch }}
          prs_json=$(gh pr list --state open \
            --base ${{ inputs.base_branch }} \ 
            --head ${{ inputs.head_branch }} \
            --json url)
          echo $prs_json
          echo "::set-output name=prs::$prs_json"

  create-pr:
    name: Create release PR

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      repository-projects: read  # Needed to add labels

    needs: check-for-existing-pr

    # Only run if no existing release PRs exist
    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] == null }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          gh pr create \
            --base ${{ inputs.base_branch }} \
            --head ${{ inputs.head_branch }} \
            --title "Merge dev into main - $(date +%F)" --body hi --label release

      # Adding labels in one step using the CLI doesn't work via actions
      - name: Add release label
        run: |
          pr_num=$(gh pr list --state open \
            --base ${{ inputs.base_branch }} \
            --head ${{ inputs.head_branch }} \
            --json number | jq '.[0].number')
          gh pr edit $pr_num --add-label release

  pr-exists:
    name: Release PR already exists

    runs-on: ubuntu-latest

    needs: check-for-existing-pr

    # Only run if no existing release PRs exist
    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] != null }}

    steps:
      - name: Release PR already exists
        run: echo ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0].url }}
