name: Create release PR

# Run on pushes to dev branch or manual trigger
on:
  push:
    branches:
      - 'dev'  # Create a PR as soon as there is at least one commit
  workflow_dispatch:

jobs:
  create-release-pr:
    name: Create release pull request

    permissions:
      pull-requests: write
      contents: read
      repository-projects: read

    uses: ./.github/workflows/auto-create-pr.yml

    with:
      base_branch: main
      head_branch: dev
      title: Advance main release to dev - $(date +%F)
      body: |
        # hi
        Test
        line
        \`dfls\`
        **afsadf**
        ~~ooooooo~~

    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
