name: Create backmerge PR

# Run on pushes to dev branch or manual trigger
on:
  push:
    branches:
      - 'main'  # Create a PR as soon as there is at least one commit
  workflow_dispatch:

jobs:
  create-backmerge-pr:
    permissions:
      pull-requests: write
      contents: read
      repository-projects: read

    uses: ./.github/workflows/auto-create-pr.yml

    with:
      base_branch: dev
      head_branch: main
      title: Backmerge main into dev - $(date +%F)
      body: hi

    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
