name: Create release PR

# Run on pushes to dev branch or manual trigger
on:
  push:
    branches:
      - 'dev'  # Create a PR as soon as there is at least one commit
  workflow_dispatch:

jobs:
  create-release-pr:
    permissions:
      pull-requests: write
      contents: read
      repository-projects: read  # Needed to add labels

    uses: ./.github/workflows/auto-create-pr.yml
    with:
      base_branch: main
      head_branch: dev
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
