name: Create release PR

# Run on pushes to dev branch or manual trigger
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
 
permissions:
  pull-requests: write
  contents: read

jobs:
  check-for-existing-pr:
    name: Check for existing PR

    runs-on: ubuntu-latest

    outputs:
      prs: ${{ steps.check.outputs.prs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Output JSON to output called prs
      - id: check
        name: Check for existing PRs
        run: | 
          prs_json=$(gh pr list --state open --base main --head dev --json url)
          echo $prs_json
          echo "::set-output name=prs::$prs_json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-pr:
    name: Create release PR

    runs-on: ubuntu-latest

    needs: check-for-existing-pr

    # Only run if no existing release PRs exist
    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] == null }}

    # Use default github actions token for gh CLI
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: gh pr create --base main --head dev --title "Merge dev into main - $(date +%F)" --body hi --label release

      # Adding labels in one step using the CLI doesn't work via actions
      - name: Add release label
        run: |
          pr_num=$(gh pr list --state open --base main --head dev --json number | jq '.[0].number')
          gh pr edit $pr_num --add-label release

  pr-exists:
    name: Release PR already exists

    runs-on: ubuntu-latest

    needs: check-for-existing-pr

    # Only run if no existing release PRs exist
    if: ${{ fromJSON(needs.check-for-existing-pr.outputs.prs)[0] != null }}

    steps:
      - name: Release PR already exists
        run: echo ${{ needs.check-for-existing-pr.outputs.prs }}
