# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        run: gh pr create --base main --head dev --title "Merge dev into main - $(date +%F)" --body hi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
